export interface PartyQuestions{
    question: string,
    background: string
}


export interface PartyQuestionsResponse {
    questions: PartyQuestions[];

}


export const questionsniveau1 =  [
    "Tous les maillots de bain deux pièces, vous buvez nbre1 gorgée(s).",
    "Tous les maillots unicolores ça saute dans l’eau.",
    "name1 fais nous un plongeon de type olympique ou bois nbre1 gorgée(s).",
    "name1 et name2 font une compétition de plonger, voter pour le meilleur. Il distribue nbre1 gorgée(s).",
    "Le dernier qui saute dans l’eau prends un cul-sec.",
    "Votez pour qui a le plus maillot de bain, le gagnant boit nbre1 gorgée(s).",
    "Tous ceux avec des lunettes de soleil, vous buvez nbre1 gorgée(s).",
    "name1 si tu es plus bronzé que name2, distribue nbre1 gorgée(s).",
    "Tous ceux qui ont un coup de soleil, c’est nbre1 gorgée(s).",
    "Tous ceux qui sont à l’ombre, c’est nbre1 gorgée(s).",
    "Tous ceux qui se sont baignés boivent nbre1 gorgée(s).",
    "name1 si tu es allé dans l’eau avant name2, tu bois nbre1 gorgée(s) sinon distribue.",
    "Tous ceux qui n’ont pas pied partout dans la piscine boivent nbre1 gorgée(s).",
    "Celui qui saute le plus loin possible dans la piscine, distribue nbre1 gorgée(s).",
    "Le premier qui touche le fond de la piscine avec le nez, distribue nbre1 gorgée(s).",
    "Le premier qui touche le fond de la piscine avec la main, distribue nbre1 gorgée(s).",
    "name1 et name2 sont en compétition, celui qui fais le plus beau papillon distribue nbre1 gorgée(s).",
    "name1 et name2 sont en compétition, celui qui fais le plus beau dos crawlé distribue nbre1 gorgée(s).",
    "Concours de Saut : Voter pour la plus belle figure, le gagnant distribue nbre1 gorgée(s).",
    "name1 si tu arrives à t’assoir en tailleur au fond de l’eau, distribue nbre1 gorgée(s) sinon c’est pour toi.",
    "name1 si tu arrives à t’allonger au fond de l’eau, distribue nbre1 gorgée(s).",
    "C’est l’heure de la joute : name1 et name2, choisissez un partenaire chacun pour faire équipe dans la piscine. Monter sur les épaules de votre partenaire. La première équipe à tomber prends un cul-sec.",
    "Tous ceux qui ne sont pas épilés, c’est nbre1 gorgée(s).",
    "Tous ceux qui ont un slip de bain, c’est un cul-sec.",
    "Le propriétaire de la piscine, il distribue nbre1 gorgée(s) parce que c’est sympa de partager sa piscine.",
    "name1 si tu arrives à faire le poirier, tu distribues nbre1 gorgée(s).",
    "name1 doit sauter dans l’eau tout habiller.",
    "name1 désigne une personne qui doit sauter si elle refuse elle boit nbre1 gorgée(s).",
    "name1 et name2, faites nous une petite nage synchronisé ou sinon vous buvez nbre1 gorgée(s).",
    "name1 et name2, sauté en même temps dans l’eau, si vous refusez c’est nbre1 gorgée(s).",
    "Concours de bombe : Voter pour la plus belle bombe, le gagnant distribue nbre1 gorgée(s).",
    "Tous ceux qui ne se sont pas encore baigné, plongé ou vous buvez nbre1 gorgée(s).",
    "Ouistitizz ! name1 prends un selfie avec tous les participants. Ça vous fera des souvenirs.",
    "Tous les maillots de bain bleu boivent nbre1 gorgée(s).",
    "Tous les maillots de bain rouge boivent nbre1 gorgée(s).",
    "Tous ceux qui ont des masques boivent nbre1 gorgée(s).",
    "Toutes celles qui ont un maillot de bain une pièce, vous buvez nbre1 gorgée(s).",
    "name1 jette tes lunettes dans la piscine, si tu les récupères avant qu’elles touchent le fond tu distribues nbre1 gorgée(s), sinon tu bois.",
    "Tous ceux qui font des plats et qui pensent savoir plonger, c’est nbre1 gorgée(s).",
    "name1 fais une roulade avant dans l’eau ou bois nbre1 gorgée(s).",
    "name1 fais une roulade arrière dans l’eau ou bois nbre1 gorgée(s).",
    "name1 et name2 faites un poirier. Votez pour le plus beau poirier, le perdant bois nbre1 gorgée(s).",
    "Tous ceux qui ont des maillots de bains rayés, c’est nbre1 gorgée(s).",
    "Tous ceux qui ont des maillots de bains avec des motifs, c’est nbre1 gorgée(s).",
    "Tous ceux qui sont en sous-vêtements et non en maillot de bain, c’est nbre1 gorgée(s).",
    "Tous ceux qui ont une casquette boivent nbre1 gorgée(s).",
    "Tous ceux qui ont un bob distribuent nbre1 gorgée(s).",
    "Tous ceux qui n’ont pas mis de crème solaire, c’est nbre1 gorgée(s).",
    "Tous ceux qui ont une serviette bleue, c’est nbre1 gorgée(s).",
    "Tous ceux qui n’ont pas pris de serviettes, c’est nbre1 gorgée(s).",
    "Tous ceux qui ont une serviette avec des motifs, distribuent nbre1 gorgée(s).",
    "Tous ceux qui boivent une piscine distribuent nbre1 gorgée(s).",
    "name1 donne nous la température de l’eau, si elle est à moins de 22° C, vous prenez tous un cul-sec.",
    "Course : name1 et name2 font la nage du petit chien, le premier à arriver au bout de la piscine distribue.",
    "Aller tous à l’eau ! c’est l’heure de la bataille d’eau, ceux qui refusent boivent nbre1 gorgée(s).",
    "Tous ceux qui ont du vernis boivent nbre1 gorgée(s).",
    "Tous ceux qui ont la marque du bronzage à cause de leur t-shirt, c’est nbre1 gorgée(s).",
    "Plongeon : name1 mets-toi au milieu de la piscine, name2 doit plonger et passer sous tes jambes. S’il rate, il boit nbre1 gorgée(s).",
    "Course : faites un aller sans les mains, le gagnant distribue nbre1 gorgée(s). name1 c’est toi l’arbitre.",
    "Course : faites un aller sans les jambes, le gagnant distribue nbre1 gorgée(s). name1 c’est toi l’arbitre.",
    "Tous ceux qui savent plonger en arrière, prouvez-le ! Si vous y arrivez-vous distribuez nbre1 gorgée(s).",
    "Tous ceux qui ont déjà fait de la natation en club boivent nbre1 gorgée(s).",
    "Le cercle de feu : name1 et name2, font un cercle avec leurs bras, les autres doivent passer à travers en plongeant. Ceux qui échouent boivent nbre1 gorgée(s). #nemo.",
    "Compétition : Le premier qui touche le fond de la piscine entre name1 et name2, il distribue nbre1 gorgée(s).",
    "Tous ceux qui ont un chapeau boivent nbre1 gorgée(s).",
    "Le premier qui se met sur la bouée gonflable distribue nbre1 gorgée(s).",
    "Tous ceux qui sont sur des chaises longues boivent nbre1 gorgée(s).",
    "Tous ceux qui ont les pieds dans l’eau boivent nbre1 gorgée(s).",
    "Celui qui a dû gonfler la bouée gonflable distribue nbre1 gorgée(s).",
    "Tous ceux qui ont mangé avant d’aller dans l’eau boivent nbre1 gorgée(s).",
    "name1 et name2, faites un plat. Votez pour le plus beau, le gagnant distribue nbre1 gorgée(s).",
    "Tous ceux qui sont en tong boivent nbre1 gorgée(s).",
    "Votez pour le meilleur nageur, le gagnant boit nbre1 gorgée(s).",
    "Tous ceux qui ont emprunté un maillot de bain boivent nbre1 gorgée(s).",
    "Tous ceux qui ont des glaçons dans leur verre boivent nbre1 gorgée(s).",
    "Toutes celles qui sont topless boivent nbre1 gorgée(s).",
    "Tous ceux qui sont pieds nu boivent nbre1 gorgée(s).",
    "name1 va dans la piscine et essaye de marcher sur les mains. Si tu arrives distribues nbre1 gorgée(s).",
    "name1 si tu sais faire un salto avant distribue nbre1 gorgée(s).",
    "name1 si tu sais faire un salto arrière distribue nbre1 gorgée(s).",
    "name1 et name2, faites une course en crawl. Le premier arrivé distribue nbre1 gorgée(s).",
    "Celui ou celle qui a pensé à prendre de la crème solaire distribue nbre1 gorgée(s).",
    "name1 si tu nages plus vite que name2 distribue nbre1 gorgée(s). Au passage, prouve-le !",
    "name1 saute sur la bouée gonflable, si tu arrives à rester dessus distribues nbre1 gorgée(s), sinon tu les bois.",
    "name1 plonge sous la bouée gonflable, si tu échoues bois nbre1 gorgée(s).",
    "Tous ceux qui ont déjà des verrues à cause de la piscine boivent nbre1 gorgée(s).",
    "Tous ceux qui étaient dispensé de piscine à l’école boivent nbre1 gorgée(s).",
    "name1 monte sur les épaules de name2 dans la piscine. Si tu refuses bois nbre1 gorgée(s).",
    "Le premier à réussir à pousser name1 dans l’eau distribue nbre1 gorgée(s).",
    "Le dernier à finir son verre saute dans la piscine.",
    "Tous ceux qui ne savent pas ce qu’est un skimmer boivent nbre1 gorgée(s).",
    "Le dernier à être allé dans une piscine publique boit nbre1 gorgée(s).",
    "Cul-sec ! Tous à l’eau, c’est l’heure de s’amuser un peu.",
    "name1 donne nous un nom de nageur célèbre. Si tu ne sais pas, bois nbre1 gorgée(s).",
    "name1 si tu as déjà eu une mauvaise aventure à cause de la piscine raconte-nous ou bois nbre1 gorgée(s).",
    "name1 et name2, vous échangez de verre.",
    "name1 épelle le mot piscine à l’envers en moins de 5 secondes. Si tu échoues bois nbre1 gorgée(s) et saute dans l’eau.",
    "name1 sautes dans l’eau ou bois nbre1 gorgée(s).",
    "name1 et name2, sautez dans l’eau ou buvez nbre1 gorgée(s).",
    "Compétition : name1 et name2, vous êtes chef d’équipe, composé 2 équipes.",
    "Mettez-vous en file indienne, le dernier de la file doit plonger et passer sous les jambes de ses coéquipiers. La première équipe à toucher le bord opposé de la piscine gagne. Les perdants boivent nbre1 gorgée(s)."
]


export const questionsniveau2 =  [
    "name1, c’est ta tournée !",
    "name1 échange ton verre avec name2",
    "Tous ceux qui ont payé en carte, boivent nbre1 gorgée(s).",
    "Tous ceux qui ont bu plus de deux verres, c’est nbre1 gorgée(s).",
    "Tous ceux qui sont en bout de table, c’est nbre1 gorgée(s).",
    "Tous ceux qui ont ajouté des chaises à la table, c’est nbre1 gorgée(s).",
    "Tous ceux qui sont sur un tabouret, c’est nbre1 gorgée(s).",
    "Tous ceux qui n’ont pas de liquide c’est nbre1 gorgée(s).",
    "name1 si tu as commandé à manger, c’est nbre1 gorgée(s).",
    "name1 si tu as mangé avant, c’est nbre1 gorgée(s).",
    "Tous ceux qui ont pris un cocktail, vous buvez nbre1 gorgée(s).",
    "name1 et name2, celui qui connaît le plus de prénom de serveur / serveuse, distribue nbre1 gorgée(s).",
    "name1 si tu as pris une bière, c’est nbre1 gorgée(s).",
    "Tous ceux qui sont déjà venu dans ce bar boivent nbre1 gorgée(s).",
    "name1 si tu rentres en transport en commun, distribue nbre1 gorgée(s).",
    "name1 si tu dors chez name2 ce soir, tu bois nbre1 gorgée(s).",
    "Tous ceux qu’ont incrusté leur pote à la soirée, c’est un cul-sec.",
    "Tous ceux qui ont un jeu de carte sur eux distribuent nbre1 gorgée(s).",
    "name1 paye un verre à name2, si il/elle refuse, il prend nbre1 gorgée(s).",
    "Tous ceux qui ont payé un verre à quelqu’un distribuent nbre1 gorgée(s).",
    "name1 choisit un cocktail/alcool que name2 devra boire, si il/elle refuse il/elle paye sa tournée.",
    "Tous ceux qui ont fait les malin en prenant un cocktail inconnu au bataillon, c’est nbre1 gorgée(s). On espère que c’est bon !",
    "name1 si tu as pris un shot, reprends un !",
    "name1 si ton verre est plus rempli que celui de name2, fini-le !",
    "Le dernier arrivé paye un shot à l’organisateur de la soirée.",
    "name1 si toi aussi tu devais pas sortir, bois nbre1 gorgée(s).",
    "Tous ceux qui ont pris un Jägerbomb, c’est l’heure d’en commander un autre.",
    "name1 si le serveur ou la serveuse de te donne son numéro, tout le monde doit prendre un shot.",
    "name1 et name2, le premier à avoir le numéro de quelqu’un du bar hors participants, distribue nbre1 gorgée(s).",
    "name1 et name2, le premier à se faire offrir une clope, distribue nbre1 gorgée(s).",
    "Tous ceux qui ont déjà taxés des clopes boivent nbre1 gorgée(s).",
    "name1 si tu as payé un verre à quelqu’un de la soirée, distribue nbre1 gorgée(s).",
    "name1 commandes un 1m de shots.",
    "name1 commandes un demi mètre de shots.",
    "Le dernier à avoir vomi dans un bar, boit nbre1 gorgée(s).",
    "Je m’en vais au bar, et je commande un… name1 tu commences. Le suivant doit répéter et ajouter une boisson. Le perdant boit nbre1 gorgée(s).",
    "name1 raconte une histoire. Devinez si c'est vrai ou faux, ceux qui se sont trompés c’est un shot.",
    "Tous ceux qui sont venu en scooter boivent nbre1 gorgée(s).",
    "Tous ceux qui ont bu plus de deux alcool différent boivent nbre1 gorgée(s).",
    "name1 et name2 échangent de place.",
    "name1 va accoster un inconnu ou bois nbre1 gorgée(s).",
    "name1 fais un flip de ton dessous de verre, si tu réussis distribues nbre1 gorgée(s). Sinon c’est pour toi.",
    "Tous ceux qui sont venus en vélo distribuent nbre1 gorgée(s).",
    "name1 raconte nous ta dernière cuite dans un bar ou bois nbre1 gorgée(s).",
    "Tous ceux qui ont déjà pécho dans ce bar boivent nbre1 gorgée(s).",
    "Tous ceux qui ont déjà pécho un serveur ou une serveuse distribuent nbre1 gorgée(s).",
    "Tous ceux qui ont déjà dépensé beaucoup d’argent dans ce bar boivent nbre1 gorgée(s).",
    "name1 lance un tour de je n’ai jamais.",
    "Tout le monde boit nbre1 gorgée(s) dans le verre de son voisin de droite.",
    "name1 finis-le verre de name2.",
    "Tous ceux qui ont pris un mojito distribuent nbre1 gorgée(s).",
    "name1 si ton verre est vide recommandes en un autre.",
    "Voter pour la personne qui tient le moins bien l’alcool, il devra boire nbre1 gorgée(s).",
    "Tous ceux qui ont un verre à pied boivent nbre1 gorgée(s).",
    "Tous ceux qui ont tiré de l’argent avant de venir boivent nbre1 gorgée(s).",
    "Tous ceux qui ont prévu de se mettre une grosse race ce soir boivent nbre1 gorgée(s).",
    "Tous ceux qui sont déprimés boivent nbre1 gorgée(s).",
    "Tous ceux qui doivent rentrer tôt boivent nbre1 gorgée(s).",
    "name1 commande un verre de ton choix à name2, il sera obligé de le boire.",
    "name1 épelle le nom du bar en moins de 5 secondes. Si tu échoues bois nbre1 gorgée(s).",
    "name1 épelle le nom de ta boisson en moins de 5 secondes. Si tu échoues bois nbre1 gorgée(s).",
    "name1, c’est ta tournée !",
    "name1 échange ton verre avec name2",
    "Tous ceux qui ont payé en carte, boivent nbre1 gorgée(s).",
    "Tous ceux qui ont bu plus de deux verres, c’est nbre1 gorgée(s).",
    "Tous ceux qui sont en bout de table, c’est nbre1 gorgée(s).",
    "Tous ceux qui ont ajouter des chaises à la table, c’est nbre1 gorgée(s).",
    "Tous ceux qui sont sur un tabouret, c’est nbre1 gorgée(s).",
    "Tous ceux qui n’ont pas de liquide c’est nbre1 gorgée(s).",
    "name1 si tu as commandé à manger, c’est nbre1 gorgée(s).",
    "name1 si tu as mangé avant, c’est nbre1 gorgée(s).",
    "Tous ceux qui ont pris un cocktail, vous buvez nbre1 gorgée(s).",
    "name1 et name2, celui qui connaît le plus de prénom de serveur / serveuse, distribue nbre1 gorgée(s).",
    "name1 si tu as pris une bière, c’est nbre1 gorgée(s).",
    "Tous ceux qui sont déjà venu dans ce bar boivent nbre1 gorgée(s).",
    "name1 si tu rentres en transport en commun, distribue nbre1 gorgée(s).",
    "name1 si tu dors chez name2 ce soir, tu bois nbre1 gorgée(s).",
    "Tous ceux qu’ont incrusté leur pote à la soirée, c’est un cul-sec.",
    "Tous ceux qui ont un jeu de carte sur eux distribuent nbre1 gorgée(s).",
    "name1 paye un verre à name2, si il/elle refuse, il prend nbre1 gorgée(s).",
    "Tous ceux qui ont payé un verre à quelqu’un distribuent nbre1 gorgée(s).",
    "name1 choisit un cocktail/alcool que name2 devra boire, si il/elle refuse il/elle paye sa tournée.",
    "Tous ceux qui ont fait les malin en prenant un cocktail inconnu au bataillon, c’est nbre1 gorgée(s). On espère que c’est bon !",
    "name1 si tu as pris un shot, reprends un !",
    "name1 si ton verre est plus rempli que celui de name2, fini-le !",
    "Le dernier arrivé paye un shot à l’organisateur de la soirée.",
    "name1 si toi aussi tu devais pas sortir, bois nbre1 gorgée(s).",
    "Tous ceux qui ont pris un Jägerbomb, c’est l’heure d’en commander un autre.",
    "name1 si le serveur ou la serveuse de te donne son numéro, tout le monde doit prendre un shot.",
    "name1 et name2, le premier à avoir le numéro de quelqu’un du bar hors participants, distribue nbre1 gorgée(s).",
    "name1 et name2, le premier à se faire offrir une clope, distribue nbre1 gorgée(s).",
    "Tous ceux qui ont déjà taxés des clopes boivent nbre1 gorgée(s).",
    "name1 si tu as payé un verre à quelqu’un de la soirée, distribue nbre1 gorgée(s).",
    "name1 commandes un 1m de shots.",
    "name1 commandes un demi mètre de shots.",
    "Le dernier à avoir vomi dans un bar, boit nbre1 gorgée(s).",
    "Je m’en vais au bar, et je commande un… name1 tu commences. Le suivant doit répéter et ajouter une boisson. Le perdant boit nbre1 gorgée(s).",
    "name1 raconte une histoire. Devinez si c'est vrai ou faux, ceux qui se sont trompés c’est un shot.",
    "Tous ceux qui sont venu en scooter boivent nbre1 gorgée(s).",
   "Tous ceux qui ont bu plus de deux alcool différent boivent nbre1 gorgée(s)."
]